name: End-to-end tests
on:
  push:
    branches: "*"

jobs:
  test:
    runs-on: ubuntu-18.04

    steps:
      - name: Install end-to-end test dependencies
        run: |
          sudo apt update
          # chromium dependencies
          sudo apt-get install libgbm1
          # ffmpeg
          sudo apt-get install -y ffmpeg

      - uses: actions/setup-node@v1

      - name: Add yarn global bin to path
        run: echo "::add-path::$(yarn global bin)"

      - uses: actions/checkout@v2
        with:
          path: ./vuepress

      - name: Install and register VuePress
        run: |
          yarn
          yarn register-vuepress
          yarn tsc
        working-directory: ./vuepress

      - name: Create test project
        run: |
          mkdir test_project
          cd test_project
          yarn init -y
          yarn link vuepress
          echo '# Hello VuePress' > README.md

      - name: Run VuePress
        run: vuepress dev &
        working-directory: ./test_project

      - run: npx qawolf test --headless initialSetup
        env:
          FFMPEG_PATH: /usr/bin/ffmpeg # for recording video
          QAW_ARTIFACT_PATH: ${{ github.workspace }}/artifacts # save video and logs

      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@master
        with:
          name: qawolf
          path: ${{ github.workspace }}/artifacts
